# Generated by Django 2.2 on 2021-08-23 15:26

from django.db import migrations, models
import hopbox_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('hopbox_app', '0002_auto_20210823_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='option_id',
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(validators=[hopbox_app.models.review_validator]),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=255, validators=[hopbox_app.models.address_validator]),
        ),
        migrations.AlterField(
            model_name='user',
            name='firstname',
            field=models.CharField(max_length=255, validators=[hopbox_app.models.name_validator]),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastname',
            field=models.CharField(max_length=255, validators=[hopbox_app.models.name_validator]),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255, validators=[hopbox_app.models.password_validator]),
        ),
    ]
