# Generated by Django 2.2 on 2021-08-24 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopbox_app', '0003_auto_20210823_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='box_name',
            field=models.CharField(default='custom', max_length=255),
        ),
    ]
