# Generated by Django 2.2 on 2021-08-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopbox_app', '0004_subscription_box_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_alt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_path',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
